### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Zaseth** [SwampApe/node-amf#1]
Hi 👋

I noticed your project that you're working on. It's pretty interesting to see that someone's working on AMF! I myself made an AMF library as well which you can find [here](https://github.com/Zaseth/bytearray-node) and I'm hoping it'll help you.

May I know what this is for exactly?

**Comment by SwampApe** [comment]
Thanks! I was writing an RTMP server in node and thought I'd just write everything from scratch to learn. I'll check out your repo sometime soon!

**Comment by Zaseth** [comment]
.
